# JdbcTemplate Query Logging
logging.level.org.springframework.jdbc.core.JdbcTemplate: debug

# JPA
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
#logging.level.org.hibernate.type=trace

greeting:
  welcome: You are using ${spring.application.name}

taco:
  orders:
    pageSize: 10