# JPA
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
  data:
    rest:
      base-path: /api
  jms:
    template:
      default-destination: tacocloud.order.queue
#logging.level.org.hibernate.type=trace


greeting:
  welcome: You are using ${spring.application.name}

taco:
  orders:
    pageSize: 10

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug
    tacos: debug